const words = [
  "javascript",
  "function",
  "variable",
  "syntax",
  "browser",
  "developer",
  "coding",
  "algorithm",
  "interface",
  "keyboard",
  "monitor",
  "database",
  "python",
  "application",
  "network",
  "test",
  "method",
  "artificial",
  "synthetic",
  "software",
  "dynamic",
  "packet",
  "internet",
  "development",
  "debugging",
  "debug",
  "c##",
  "linux",
  "windows",
  "mac",
  "unix",
  "google",
  "API",
  "bug",
  "integration",
  "recursive",
  "regressive",
  "adjacent",
  "encryption",
  "IDE",
  "library",
  "loop",
  "integer",
  "bool",
  "boolean",
  "git",
  "hardcode",
  "bash",
  "bandwidth",
  "benchmark",
  "binary",
  "hex",
  "hexadecimal",
  "bit",
  "bitrate",
  "byte",
  "class",
  "cryptography",
  "computation",
  "emulator"
];

const phrases = [
  "data scientist",
  "operating system",
  "software engineer",
  "object oriented programming",
  "rainbow garden",
  "metal harbor",
  "big O notation",
  "cloud computing",
  "data structure",
  "justify-content:",
  "float: left;",
  "font-size: 1rem;",
  "padding: 10px;",
  "margin-top: 5px;",
  "kino casino",
  "Visual Studio Code",
  "Unity Engine",
  "Quick brown fox",
  "Lazy dog naps",
  "data types",
  "version control",
  "binary tree",
  "binary search",
  "words per minute",
  "edge case"
]

const sentences = [
  "The quick brown fox jumps over 13 lazy dogs",
  "A friend loves at all times, and a brother is born for a time of adversity.",
  "That's one small step for man, one giant leap for mankind",
  "Do unto others as you would have them do unto you.",
  "You never change your life until you step out of your comfort zone; change begins at the end of your comfort zone.",
  "If the freedom of speech is taken away then dumb and silent we may be led, like sheep to the slaughter.",
  "Do not pray for easy lives, my friends. Pray to be stronger men.",
  "The phone was broken, but he was sick of buying new ones. He grabbed his screwdriver and contemplated how to attack the problem. It was probably beyond his ability, but he was damn good with a screwdriver. After drinking three of them it wasn't fixed, but he didn't care anymore.",
  "I am working today.",
  "I am cleaning the room.",
  "She is serving a guest.",
  "He is cooking dinner.",
  "We are cleaning the kitchen.",
  "They are checking the rooms.",
  "There is a guest in the lobby.",
  "The server is bringing the menu.",
  "The cook is making lunch.",
  "The barista is making coffee.",
  "The cleaner is mopping the floor.",
  "The receptionist is helping a guest.",
  "I do not work today.",
  "I do not clean rooms.",
  "She does not cook lunch.",
  "He does not answer the phone.",
  "We do not start work today.",
  "The housekeeper is vacuuming the floor.",
  "She is mopping the floor.",
  "He is taking out the trash.",
  "She is making the bed.",
  "The barista is making coffee.",
  "The cook is preparing breakfast.",
  "The cook is cutting vegetables.",
  "The cook is washing plates.",
  "The server is setting the table.",
  "The server is taking an order.",
  "The server is carrying plates.",
  "The server is refilling water.",
  "The receptionist is answering emails.",
  "The receptionist is answering the phone.",
  "The receptionist is printing information.",
  "The receptionist is calling a taxi.",
  "The receptionist is making a reservation.",
]

const week_1_curriculum_words = [
  "I",
  "you",
  "he",
  "she",
  "we",
  "they",
  "name",
  "job",
  "cook",
  "cleaner",
  "manager",
  "receptionist",
  "barista",
  "server",
  "I am Ana.",
  "My name is Luis.",
  "What is your name?",
  "I am a cook.",
  "She is a server.",
  "He is a barista.",
  "We are cleaners.",
  "They are guests.",
  "This is the hotel.",
  "The guest is here.",
  "The room is clean.",
  "The restaurant is open.",
  "The manager is here.",
  "The broom is here.",
  "The towl is clean.",
  "The basket is full.",
  "The coffee machine is hot.",
  "The tray is on the table.",
  "The plate is clean.",
  "The menu is on the table.",
  // ^^ Requested ones, ones I added vv
  "read",
  "clean",
  "I am John.",
  "I am Samantha",
  "I am Anthony",
  "My name is Tony.",
  "The towl is dirty.",
  "The basket is empty.",
  "The plate is dirty.",
  "She is a barista.",
  "They are cleaners.",
  "I am a server.",
  "You are a manager.",
  "The room is dirty.",
  "I am a barista."
]

// Resting keys
const week_1_curriculum_random = [
  "asdfjkl;",
  ";lkjfdsa",
  "asfjk;alskd fdalkj;as",
  "asdf jkl;",
  "asdf jkl;",
  "aaaa ssss dddd ffff",
  "jjjj kkkk llll ;;;;",
  "asdf asdf jkl; jkl;",
  "asdf fdsa",
  "jkl; ;lkj",
  "asd sdf dfs",
  "jkl kl; l;k",
  "asdf jkl; ;lkj fdsa",
  "asdf jkl; asdf jkl; fdsa ;lkj asdf jkl;",
  "asdf fdsa jkl; ;lkj asdf jkl; fdsa ;lkj",
  "aj sk dl f;",
  "ja ks ld ;f",
  "asas dfdf",
  "jkjkl;l;",
  "fjdksla;",
  "asdf jkl;",
  "asdf jkl;",
  "fdsa ;lkj",
  "fdsa ;lkj",
  "asd asd asd",
  "jkl jkl jkl",
  "fds fds fds",
  "lkj lkj lkj",
  "sad sad sad",
  "kl; kl; kl;",
  "aa jj ss kk",
  "ddd lll fff ;;;",
  "aa jj ss kk dd ll ff ;;",
  "asdf jkl; asdf jkl;",
  "aj sk dl f; aj sk dl f;",
  "fdsa ;lkj fdsa ;lkj",
  "aa ss dd ff jj kk ll ;;",
  "ajskdlf; ajskdlf;",
  ";fldksja ;fldksja",
  "asdf fdsa jkl; ;lkj",
  "aj sk dl f; asdf jkl; fdsa ;lkj",
  "aa jj ss kk dd ll ff ;; ajskdlf; ;fldksja",
  "fjdksa;l",
  "l;asdkfj",
  "afdk sjl;",
  "j;la fdsk",
  "aksl dfj;",
  "sal; dkjf",
  "falk sjd;",
  "dajf slk;",
  "lj;f dksa",
  "skaf jdl;",
  "afdj ksl;",
  "jsla fdk;",
  "dkas lfj;",
  "flas jkd;",
  "sjdf lak;",
  "akdj slf;",
  "lk;f dsaj",
  "dafj lks;",
  "slaf djk;",
  "fa; ldkj",
  "ajdl sfk;",
  "ssaa kkjj",
  "ddff ll;;",
  "asdf ;lkj",
  "afsj dkl;",
  "dask fjl;",
  "faks jdl;",
  "lasd ;jfk",
  "klas djf;",
  "jfad slk;",
  "sdaf l;kj",
]

const week_2_curriculum_words = [
  "There is a kitchen.",
  "There is a lobby.",
  "There is a bathroom.",
  "There is an office.",
  "There is a window.",
  "There are two rooms.",
  "There are many guests.",
  "There are two elevators.",
  "There are chairs in the lobby.",
  "The guest is in the room.",
  "The bar is on the first floor.",
  "The office is next to the lobby.",
  "The front desk is at the entrance.",
  "The bathroom is next to the kitchen.",
  "The elevator is near the stairs.",
  "The guest is in the elevator.",
  "The cleaner is in the hallway.",
  "The receptionist is at the front desk.",
  "The car is in the parking lot.",
  "The guest is at the bar.",
  // ^^ Requested ones, ones I added vv
  "There are four rooms.",
  "There are three elevators.",
  "The cleaner is in the elevator.",
  "There are people in the lobby.",
  "There is a hallway.",
  "There is a dining room.",
  "There is a parking lot.",
  "There is a staircase.",
  "There is a front desk.",
  "There is a restaurant.",
  "There is a guest room.",
  "There is a conference room.",
  "There is a balcony.",
  "There is a garden.",
  "There are three rooms.",
  "There are five guests.",
  "There are two bathrooms.",
  "There are many chairs.",
  "There are tables in the restaurant.",
  "There are lights in the hallway.",
  "There are cars in the parking lot.",
  "There are guests in the lobby.",
  "There are suitcases near the entrance.",
  "There are plants in the office.",
  "The manager is in the office.",
  "The chef is in the kitchen.",
  "The waiter is in the restaurant.",
  "The guest is at the front desk.",
  "The receptionist is in the lobby.",
  "The elevator is next to the lobby.",
  "The stairs are near the entrance.",
  "The restaurant is on the ground floor.",
  "The bathroom is near the guest room.",
  "The office is on the second floor.",
  "The guest room is next to the elevator.",
  "The hallway is between the lobby and the kitchen.",
  "The car is near the hotel.",
  "The cleaner is in the bathroom.",
  "The bellhop is at the entrance.",
  "The bar is next to the restaurant.",
  "The guests are in the conference room.",
  "The front desk is near the lobby.",
  "The window is in the guest room.",
  "The balcony is above the garden."
]

// Home row keys (Resting + Reacing + Home)
const week_2_curriculum_random = [
  "asdfgh jkl;",
  "asdfg hjkl;",
  "gfdsa ;lkjh",
  "aghs dfjk l;",
  "ag ah aj ak al a;",
  "fg fh fj fk fl f;",
  "sa sd sf sg sh sj sk sl s;",
  "asdfg hjkl;",
  "gghh ffjj ddkk ssll aa;;",
  "asdfg asdfg hjkl; hjkl;",
  "asdf jkl;",
  "asdfg hjkl;",
  "aaa sss ddd fff",
  "asd asd asd",
  "jkl jkl jkl",
  "asdf asdf asdf",
  "jkl; jkl; jkl;",
  "asa sas dsd fdf",
  "jkj klk l;l ;l;",
  "adsf fdsa",
  "jkl; ;lkj",
  "aa ss dd ff",
  "jj kk ll ;;",
  "af af af",
  "jk jk jk",
  "asl asl asl",
  "dfj dfj dfj",
  "fgh hjk",
  "asdfg ;lkjh",
  "aaaa jjjj ssss kkkk",
  "asd jkl",
  "asdf jkl;",
  "asdfg hjkl;",
  "fj fj fj",
  "dk dk dk",
  "sl sl sl",
  "aa jj ss kk dd ll ff ;;",
  "aa gg ss hh dd jj ff kk ll ;;",
  "asdfg hjkl; aghs dfjk l;",
  "asdfghjkl;asdfghjkl;",
  ";lkjhgfdsa;lkjhgfdsa",
  "agshdfjk;l",
  "asdfgh jkl;",
  "gghh ffjj ddkk ssll",
  "aghs dfjk l;",
  ";lkjh gfdsa",
  "asdfghjkl; ;lkjhgfdsa",
  "asdfg hjkl; gfdsa ;lkjh",
  "aaaa ssss dddd ffff gggg hhhh jjjj kkkk llll ;;;;",
  "aa ss dd ff gg hh jj kk ll ;;",
  "asdfghjkl; asdfghjkl;",
  ";lkjhgfdsa ;lkjhgfdsa",
  "asd sdf dfg fgh ghj hjk jkl",
  "jkl hjk ghj fgh dfg sdf asd",
  "asdfghjkl; asdfg hjkl;",
  "gfdsa ;lkjh",
  "aassddffgg hhjjkkll;;",
  "aa gg ss hh dd jj ff kk ll ;;",
  "as as as as df df df df gh gh",
  "gh gh jk jk jk jk l; l; l; l;",
  "asd asd asd fgh fgh fgh jkl jkl jkl",
  "sdf sdf sdf ghj ghj ghj hjk hjk hjk",
  "asdfg sdfgh",
  "dfghj",
  "fghjk",
  "ghjkl",
  "asdfg hjkl;",
  "asdfgh jkl;",
  "gfdsa ;lkjh",
  "aghs dfjk l;",
  "asdfghjkl; ;lkjhgfdsa",
  "aghsdfjk;l ;lkjfdshga",
  "asdfghjkl; aj sk dl f;",
]

const week_3_curriculum_words = [
  "That is a hat.",
  "This is my apron.",
  "This is a mop.",
  "This is the computer.",
  "This is the oven.",
  "That is a printer.",
  "That is a vacuum.",
  "That is a stove.",
  "That is the sink.",
  "These are gloves.",
  "These are shoes.",
  "These are shirts.",
  "These are pants.",
  "Those are buckets.",
  "Those are bottles.",
  "Those are tools.",
  // ^^ Requested ones, ones I added vv
  "This is a broom.",
  "This is my notebook.",
  "This is the monitor.",
  "This is a backpack.",
  "That is a ladder.",
  "That is the door.",
  "That is a keyboard.",
  "That is the cabinet.",
  "These are socks.",
  "These are pens.",
  "These are plates.",
  "These are towels.",
  "Those are boxes.",
  "Those are chairs.",
  "Those are windows.",
  "Those are backpacks.",
  "This is a clock.",
  "This is my jacket.",
  "This is the table.",
  "This is a flashlight.",
  "That is a fan.",
  "That is the whiteboard.",
  "That is a basket.",
  "That is the refrigerator.",
  "These are keys.",
  "These are cups.",
  "These are books.",
  "These are pencils.",
  "Those are plants.",
  "Those are pictures.",
  "Those are blankets.",
  "Those are notebooks."
]

// Top row keys
const week_3_curriculum_random = [
  "qwerty",
  "ytrewq",
  "qwerty ytrewq",
  "wertuop qwyui",
  "ertyoe poiuyt",
  "rtyuqw tywqp",
  "tyuiyu\\",
  "yuiopo \\[aw",
  "uiopyt qwiopr",
  "qwqwre] weweui",
  "ereroi rtrtpe",
  "tytyqw yuyuwr",
  "uiuier erop",
  "ioioui opopyt",
  "qweqyup werwter",
  "erteo p[]qw",
  "rtyr qwet poueq",
  "tyut top",
  "row error yuiy",
  "yoyo toy",
  "rtyui",
  "ewpoqrieqt",
  "qqqq wwww tutu ipip",
  "tutu tutu pwpw qpqp",
  "pipu qeqr qtpy",
  "poqw erui ty",
  "tyru qpwoe",
  "[uio] [iop]",
  "qwe] [wer\\",
  "ert] [rty\\",
  "tyu] [yui",
  "uio] [iop",
  "rt[y]u \\[ty]",
  "ty[u]i yu[i]o",
  "ui[o]p poiuy\\",
  "qwepoi tyru",
  "\\o [] []",
  "poiuytrewq qwertyuiop",
  "qpwoeiruty tyrueiwoqp",
  "\\ qutew qwwpetuio \\",
  "ruru eiei wowo qpqp",
  "qpqp wowo eiei ruru ttyy",
  "tpoqw qwoprqiprq utiq",
  "wqoie tuiweq qiwoqirtpo",
  "[] [] [] []",
  "qw qw er er ty ty ui ui op op",
  "poiuyqwert [\\]",
  "tyrueiwoqp qpwoeiruty",
  "qp ty ro [] \\\\",
  "iop iop qwe triewpq",
  "poi rtyqwe iewqpy",
  "[\\] qwp[rituqwpo [\\]",
  "qwqw erer tyty uiui opop"
]

const week_4_curriculum_words = [
  "Open the door.",
  "Close the window.",
  "Bring the tray.",
  "Take the plate.",
  "Make the coffee.",
  "Clean the table.",
  "Sweep the floor.",
  "Mop the floor.",
  "Wash the dishes.",
  "Cook the food.",
  "Serve the guest.",
  "Refill the water.",
  "Set the table.",
  "Call the manager.",
  "Answer the phone.",
  "Do not open the door.",
  "Do not touch the stove.",
  "Do not leave the door open.",
  "First sweep the floor.",
  "Next mop the floor.",
  "Then clean the table.",
  "Last close the room.",
  // ^^ Requested ones, ones I added vv
  "Open the cabinet.",
  "Close the gate.",
  "Bring the basket.",
  "Take the cup.",
  "Make the tea.",
  "Clean the counter.",
  "Wipe the table.",
  "Wash the pan.",
  "Dry the dishes.",
  "Cook the rice.",
  "Serve the meal.",
  "Refill the bottle.",
  "Set the chairs.",
  "Call the office.",
  "Answer the bell.",
  "Do not touch the sink.",
  "Do not open the oven.",
  "Do not leave the window open.",
  "First wash the vegetables.",
  "Next cut the bread.",
  "Then cook the soup.",
  "Last turn off the light.",
  "Open the box.",
  "Close the drawer.",
  "Bring the towel.",
  "Take the broom.",
  "Clean the sink."
]

// Bottom row keys
const week_4_curriculum_random = [
  "zxcv ,./ zxcv ,./",
  "z, x. c/ v, z, x. c/ v,",
  "zx,. cv/. zx,. cv/.",
  "z/x. c,v/ z/x. c,v/",
  "zz ,, xx .. cc // vv ,,",
  "zxcv/./, zxcv/./,",
  "xcvb xcvb xcvb xcvb",
  "vcxb vcxb vcxb vcxb",
  "cvxb cvxb cvxb cvxb",
  "vxbc vxbc vxbc vxbc",
  "xcvb bvcx xcvb bvcx",
  "cvbx vbxc cvbx vbxc",
  "vccx bbvx vccx bbvx",
  "xcvb cvbx vbxc bxcv",
  ",./v cxz/ ,./v cxz/",
  "z,v. x/c, z,v. x/c,",
  "zxcv ,.// zxcv ,.//",
  "z/. x,/ c./ v,. z/. x,/ c./ v,.",
  "z,z x.x c/c v,v",
  "zx, cv. z/ x, c. v/",
  "zxc ,./ zxc ,./",
  "v/c. x,z/ v/c. x,z/",
  "zzx ,,x cc/ vv. zzx ,,x cc/ vv.",
  "zxcv zxcv zxcv zxcv",
  "vcxz vcxz vcxz vcxz",
  "zxcz xcvx zxcz xcvx",
  "zz xx cc vv zz xx cc vv",
  "zx cv zx cv zx cv",
  "zc xv zc xv zc xv",
  "zxc xcv cvz vcz zxc xcv",
  "zv xc zv xc zv xc",
  "zxxc cvvz zxxc cvvz",
  "zxvc cvxz zxvc cvxz",
  "zzxc xccv cvvz vzcx",
  "zcvx xvcz zcvx xvcz",
  "zcvx zcvx zcvx zcvx",
  "vxcz vxcz vxcz vxcz",
  "zxcvvcxz zxcvvcxz",
  "vcxb xcvb cvbx vxcb",
  "bxcv vcxb xbcv cvxb",
  "xcvb vcbx cbvx xvbc",
  "cvxb bxvc vcbx cxvb",
  "vxbc cxvb bvcx xcbv",
  "cbvx xv// vbxc cvbx",
  "xcbv vcbx bxcv xvbc",
  "vbxc ,,xvb xbcv bcvx",
  "cvbx xcbv .xbc bxvc",
  "bxvc cvxb xvcb vcbx",
  "xcbv bvcx cvbx vxbc",
  "vcbx bxcv cxvb .,cv",
  "cbvx vxbc xcvb bvcx",
  "xvbc .,bx /cvx bx/c",
  "bcvx xcbv vcxb cvbx",
  "., ,. / cvzx mnb",
  "zxcvbnm,./",
  "b vncmx,z. b",
  "zxc cxz vbn nbv m,. .,m",
  "mnvczx nvcxxv",
  "zcbm xvn,",
  "cvnx mxnc",
  "bvmb vz",
  "bvbvbv vbvbvb bv vbvb bvbv",
  "bvbv cvcv vc bcbcbvbv cvcv vc vc",
  "xxvcbv bcbc vcvc bcvc vcbc vc cvb"
]

const week_5_curriculum_words = [
  "I wake up at six.",
  "I eat breakfast.",
  "I study English.",
  "I work in a hotel.",
  "I start work at eight.",
  "I finish work at four.",
  "I reserve a room.",
  "I print the receipt.",
  "I prepare the food.",
  "I cut vegetables.",
  "I mix the salad.",
  "I carry the plates.",
  "I check the room.",
  "It is eight o'clock.",
  "My shift starts at nine.",
  "I work on Monday.",
  "I work on Tuesday.",
  "Breakfast is at seven.",
  "Lunch is at twelve.",
  "Dinner is at six.",
  // ^^ Requested ones, ones I added vv
  "I brush my teeth.",
  "I get dressed.",
  "I go to work.",
  "I take the bus.",
  "I arrive at work early.",
  "I clean the kitchen.",
  "I wash the cups.",
  "I open the restaurant.",
  "I greet the guests.",
  "I answer the phone.",
  "I write the orders.",
  "I serve the drinks.",
  "I make the beds.",
  "I sweep the hallway.",
  "I check the schedule.",
  "It is seven o'clock.",
  "My break starts at ten.",
  "I work on Wednesday.",
  "Snack time is at three.",
  "I go home at five.",
  "I study Spanish.",
  "I work in a supermarket.",
  "I work in a zoo.",
  "I prepare the table.",
  "I start work at nine.",
  "Lunch is at eleven."
]

// All alphabet keys (top, middle/home, bottom)
const week_5_curriculum_random = [
  "asdf jkl; asdf jkl;",
  "fdsa ;lkj fdsa ;lkj",
  "aaa sss ddd fff jjj kkk lll ;;;",
  "asdfg hjkl; asdfg hjkl;",
  "qwer uiop qwer uiop",
  "poiu rewq poiu rewq",
  "qq ww ee rr uu ii oo pp",
  "qwer tyui qwer tyui",
  "zxcv nm,. zxcv nm,.",
  ".,mn vcxz .,mn vcxz",
  "zzz xxx ccc vvv nnn mmm ,,, ...",
  "zxcvb nm,./ zxcvb nm,./",
  "qaz wsx edc rfv qaz wsx edc rfv",
  "pl, okm ijn uhb pl, okm ijn uhb",
  "asdz xcfa asdz xcfa",
  "lk;j .,m/ lk;j .,m/",
  "qwe asd zxc qwe asd zxc",
  "poi lkj m,. poi lkj m,.",
  "qaz qaz wsx wsx edc edc",
  "rfv rfv tgb tgb yhn yhn",
  "ujm ujm ik, ik, ol. ol.",
  "qw as zx qw as zx",
  "er df cv er df cv",
  "ty gh bn ty gh bn",
  "ui jk nm ui jk nm",
  "op l; ,. op l; ,.",
  "qwer asdf zxcv qwer asdf zxcv",
  "poi ;lkj /.,m poiu ;lkj /.,m",
  "[] \\ [] \\ [] \\",
  ";';';';;'';;''",
  ",./,./,./,.",
  "qw[] er\\ as;' df[] zx,. cv/",
  "asdf qwer zxcv asdf qwer zxcv",
  "jkl; uiop m,./ jkl; uiop m,./",
  "aqa sws ded frf",
  "zxz xcx vcv bvb",
  "qpq owo eie rir",
  ";l; kjk hgh gfg",
  "qa za ws xs ed dc rf fv",
  "uj jm ik k, ol l. p; ;/",
  "qaz wsx edc rfv tgb",
  "yhn ujm ik, ol. p;/",
  "asdfg qwert zxcvb",
  "hjkl; yuiop nm,./",
  "asdf asdf asdf asdf",
  "fdsa fdsa fdsa fdsa",
  "jkl; jkl; jkl; jkl;",
  ";lkj ;lkj ;lkj ;lkj",
  "qwer qwer qwer qwer",
  "rewq rewq rewq rewq",
  "zxcv zxcv zxcv zxcv",
  "vcxz vcxz vcxz vcxz",
  "aqaz swsx dedc frfv",
  "zaqx xswc cder evfr",
  "asl ;fjfa s;kdgh'",
  "qwepoi lkjasd zmxncb",
  "qazplm rfvuhb",
  "bbb cvb bmb bnb bvbv bcbc xb vb",
  "fv gb dc sx fvfv bvcbvb mvnzxc",
  "plqfgfha opqwefvmncb"
]

const week_6_curriculum_words = [
  "Do you work today?",
  "Do you clean rooms?",
  "Do you cook lunch?",
  "Do you serve guests?",
  "Do you work in the hotel?",
  "Does he work here?",
  "Does she clean rooms?",
  "Does he cook dinner?",
  "Does she answer the phone?",
  "Does he print receipts?",
  "Yes, I do.",
  "No, I don't.",
  "Yes, she does.",
  "No, he doesn't.",
  // ^^ Requested ones, ones I added vv
  "Do you wash dishes?",
  "Do you make coffee?",
  "Do you start at eight?",
  "Do you work on weekends?",
  "Do you check the rooms?",
  "Does he open the store?",
  "Does she wash the towels?",
  "Does he serve breakfast?",
  "Does she work in the kitchen?",
  "Does he call the manager?",
  "Yes, he does.",
  "No, he doesn't.",
  "Yes, they do.",
  "No, they don't.",
  "Does she clean the table?",
  "Do you carry the plates?",
  "Does he prepare the food?",
  "Do you answer the phone?",
  "Does she print the receipt?",
  "Do you finish work at four?",
  "Do you open the door?",
  "Do you mop the floor?",
  "Do you refill the water?",
  "Do you set the table?",
  "Do you call the office?",
  "Does he wash the dishes?",
  "Does she make the tea?",
  "Does he clean the kitchen?",
  "Does she serve the food?",
  "Does he check the room?",
  "Yes, we do.",
  "No, we don't.",
  "Yes, he does.",
  "No, she doesn't.",
  "Does she work this morning?"
]

// Number row keys
const week_6_curriculum_random = [
  "1234 5678 9012",
  "0987 6543 2109",
  "1122 3344 5566 7788 9900",
  "!@#$ %^&* ()!@",
  "#$%^ &*() !@#$",
  "1! 2@ 3# 4$ 5% 6^ 7& 8* 9( 0)",
  "1!2@ 3#4$ 5%6^ 7&8* 9(0)",
  "!1 @2 #3 $4 %5 ^6 &7 *8 (9 )0",
  "12345 54321 67890 09876",
  "!@#$$#@! %^^% &**& ()()",
  "12 23 34 45 56 67 78 89 90",
  "!@ @# #$ $% %^ ^& &* *( ()",
  "13579 24680 13579 24680",
  "1@ 2# 3$ 4% 5^ 6& 7* 8( 9) 0!",
  "11!! 22@@ 33## 44$$",
  "1234 !@#$ 5678 %^&*",
  "9( 8* 7& 6^ 5% 4$ 3# 2@ 1!",
  "10 20 30 40 50 60 70 80 90",
  ")0 (9 *8 &7 ^6 %5 $4 #3 @2 !1",
  "1234567890",
  "!@#$%^&*()",
  "1! 1! 2@ 2@ 3# 3# 4$ 4$",
  "567890 %^&*() 567890",
  "0987612345 )(*&^!@#$",
  "12!@ 34#$ 56%^ 78&* 90()",
  "1 2 3 4 5 6 7 8 9 0",
  "! @ # $ % ^ & * ( )",
  "123 234 345 456 567",
  "!@# @#$ #$% $%^ %^&",
  "90 89 78 67 56 45 34 23 12",
  "123456789!@#$%^&*(",
  "1234567890-= !@#$%^&*()_+",
  "2468 1357 9081 7263",
  "!@#$ 1234 %^&* 5678",
  "10 98 76 54 32 10",
  ")0 *8 ^6 $4 @2 )0",
  "1! 3# 5% 7& 9( 0)",
  "`1234567890-= ~!@#$%^&*()_+",
  "+_)(*&^%$#@!~ =-0987654321`",
  "`~1!2@3#4$5%6^7&8*9(0)-_=+",
  "1_2_3_4_5",
  "10-8=2",
  "4-2=2",
  "1-5=-4",
  "100-60=40",
  "12345 6789",
  "9876 54321",
  "1298 7635 2356"
]

const week_7_curriculum_words = [
  "I do not work today.",
  "I do not clean rooms.",
  "She does not cook lunch.",
  "He does not answer the phone.",
  "We do not start work today.",
  "The housekeeper is vacuuming the floor.",
  "She is mopping the floor.",
  "He is taking out the trash.",
  "She is making the bed.",
  "The barista is making coffee.",
  "The cook is preparing breakfast.",
  "The cook is cutting vegetables.",
  "The cook is washing plates.",
  "The server is setting the table.",
  "The server is taking an order.",
  "The server is carrying plates.",
  "The server is refilling water.",
  "The receptionist is answering emails.",
  "The receptionist is answering the phone.",
  "The receptionist is printing information.",
  "The receptionist is calling a taxi.",
  "The receptionist is making a reservation.",
  // ^^ Requested ones, ones I added vv
  "I do not cook dinner.",
  "He does not wash dishes.",
  "She does not open the store.",
  "We do not serve lunch today.",
  "They do not clean the kitchen.",
  "I am sweeping the floor.",
  "She is cleaning the counter.",
  "He is washing the cups.",
  "We are preparing the food.",
  "They are serving the guests.",
  "The cleaner is wiping the table.",
  "The worker is carrying a box.",
  "The cashier is helping a customer.",
  "The manager is checking the schedule.",
  "The assistant is organizing the supplies.",
  "The teacher is writing on the board.",
  "The student is reading a book.",
  "The nurse is checking the room.",
  "The driver is opening the door.",
  "The clerk is printing a receipt.",
  "I do not wash the towels.",
  "She does not clean the bathroom.",
  "He does not make coffee today.",
  "We do not open the office on Sunday.",
  "They do not answer calls at night.",
  "The worker is sweeping the hallway.",
  "She is folding the clothes.",
  "He is cleaning the window.",
  "The chef is cooking the soup.",
  "The receptionist is checking the guest list.",
  'Jack quickly fixed the box, then wrote: "Send 2 files by 5:00!"',
  'Zoe baked 4 muffins, put them on the rack, and said: "These smell great!"',
  'Fred grabbed the map, checked Route 7, and asked: "Do we turn left here?"',
  'Vicky typed a short note: "Please bring $6.50 for lunch tomorrow."',
  'Ben opened the quiz, solved 3 math problems, and yelled: "Yes, I got 100%!"',
  "Chris packed socks, shirts, and 2 jackets before the trip on Friday.",
  'Mia wrote: "The blue vase costs $9," then placed it on the desk.',
  'Paul fixed the lamp, shut the door, and whispered: "Everything is ready now."',
  'Nina mixed flour, sugar, and 2 eggs, then asked: "Should I bake this now?"',
  "Tom checked the clock at 8:45, grabbed his bag, and ran to class."
]

// All keys pt.1
const week_7_curriculum_random = [
  "fr fr fr fr",
  "ju ju ju ju",
  "de de de de",
  "ki ki ki ki",
  "ws ws ws ws",
  "ol ol ol ol",
  "aq aq aq aq",
  "p; p; p; p;",
  "ft ft ft ft",
  "gh gh gh gh",
  "yj yj yj yj",
  "ik ik ik ik",
  "rv rv rv rv",
  "bn bn bn bn",
  "ce ce ce ce",
  "m, m, m,",
  "ty ty ty ty",
  "ui ui ui ui",
  "fgv fgv fgv fgv",
  "jhn jhn jhn jhn",
  "edc edc edc edc",
  "ik, ik, ik, ik,",
  "wsx wsx wsx wsx",
  "ol. ol. ol. ol.",
  "qaz qaz qaz qaz",
  "p;/ p;/ p;/ p;/",
  "rfv tgb yhn ujm",
  "edc rfv tgb yhn",
  "wsx edc rfv tgb",
  "aqz swx dec frv",
  "frt ghy jui kio",
  "dew rtf ghj yui",
  "aqw set dfr fgt",
  "jkl iop uhy gtf",
  "wsd erf rfv vtg",
  "olk iju yhn bgv",
  "qaz wsx edc rfv",
  "pl; okm ijn uhb",
  "frv tgb yhn ujm",
  "dez xsw cvf bgt",
  "aqz swx dcv frb",
  "pl/ ok. ij, uhm",
  "fre dsw aqz xcv",
  "jui kyl ol. p;/",
  "rtf gvb yhn ujm",
  "wsx edc rfv tgb",
  "ijn uhb ygv tfc",
  "okm ol. ik, ujm",
  "asd wer sdf ert",
  "jkl uio lkj iop",
  "q1w2 e3r4 t5y6",
  "a!s@ d#f$ g%h^",
  "z1x2 c3v4 b5n6",
  "u7i8 o9p0 j-k=",
  "q! w@ e# r$ t%",
  "a1 s2 d3 f4 g5",
  "z@ x# c$ v% b^",
  "y6u7 i8o9 p0[ ]",
  "m1,2 .3/4 n5b6",
  "q2a3 z4w5 s6x7",
  "e!d@ c# r$ f%",
  "t6g7 b8y9 h0n-",
  "u^j& m* i( k) o_",
  "p0o9 i8u7 y6t5",
  "1q 2w 3e 4r 5t",
  "!a @s #d $f %g",
  "6y 7u 8i 9o 0p",
  "^h &j k (l ) ;",
  "z1a! x2s@ c3d#",
  "v4f$ b5g% n6h^",
  "m7j& ,8k .9l(",
  "/0p) ;-[ ]='",
  "qw12 er34 ty56",
  "as!@ df#$ gh%^",
  "zx12 cv34 bn56",
  "q1a2 z3w4 x5s6",
  "e7d8 c9r0 f0g=",
  "t!g@ b#y$ h%u^",
  "i&k* ,o( l)p_",
  "1q! 2w@ 3e# 4r$",
  "a5s6 d7f8 g9h0",
  "z%x^ c&v* b(n)",
  "p0o9 i8u7 y6t5",
  "m1j2 ,k3 .l4 /;5",
  "q@w# e$r% t^y&",
  "zxc qwe asd poi lkj mnb 123 098",
  "123 abcd $%^&*",
  "123abc zyx 987",
  "qpk10928 nmzxn4 12jds",
  "ruru eiei wowo qpqp"
]

const week_8_curriculum_words = [
  "I am working today.",
  "I am cleaning the room.",
  "She is serving a guest.",
  "He is cooking dinner.",
  "We are cleaning the kitchen.",
  "They are checking the rooms.",
  "There is a guest in the lobby.",
  "The server is bringing the menu.",
  "The cook is making lunch.",
  "The barista is making coffee.",
  "The cleaner is mopping the floor.",
  "The receptionist is helping a guest.",
  "I do not work today.",
  "I do not clean rooms.",
  "She does not cook lunch.",
  "He does not answer the phone.",
  "We do not start work today.",
  "The housekeeper is vacuuming the floor.",
  "She is mopping the floor.",
  "He is taking out the trash.",
  "She is making the bed.",
  "The barista is making coffee.",
  "The cook is preparing breakfast.",
  "The cook is cutting vegetables.",
  "The cook is washing plates.",
  "The server is setting the table.",
  "The server is taking an order.",
  "The server is carrying plates.",
  "The server is refilling water.",
  "The receptionist is answering emails.",
  "The receptionist is answering the phone.",
  "The receptionist is printing information.",
  "The receptionist is calling a taxi.",
  "The receptionist is making a reservation.",
  // ^^ Requested ones, ones I added vv
  "Do you wash dishes?",
  "Do you make coffee?",
  "Do you start at eight?",
  "Do you work on weekends?",
  "Do you check the rooms?",
  "Does he open the store?",
  "Does she wash the towels?",
  "Does he serve breakfast?",
  "Does she work in the kitchen?",
  "Does he call the manager?",
  "Yes, he does.",
  "No, he doesn't.",
  "Yes, they do.",
  "No, they don't.",
  "Does she clean the table?",
  "Do you carry the plates?",
  "Does he prepare the food?",
  "Do you answer the phone?",
  "Does she print the receipt?",
  "Do you finish work at four?",
  "Do you open the door?",
  "Do you mop the floor?",
  "Do you refill the water?",
  "Do you set the table?",
  "Do you call the office?",
  "Does he wash the dishes?",
  "Does she make the tea?",
  "Does he clean the kitchen?",
  "Does she serve the food?",
  "Does he check the room?",
  "Yes, we do.",
  "No, we don't.",
  "Yes, he does.",
  "No, she doesn't.",
  "Does she work this morning?",
  "Please send the email by noon.",
  "Did you check the message?",
  "I will write back later.",
  "The report is ready now.",
  "Can you open the file?",
  "She sent the receipt today.",
  "He answered the phone quickly.",
  "We finished the task early.",
  "They closed the office at five.",
  "I printed the schedule this morning.",
  "Do not forget the password.",
  "Type the address carefully.",
  "The subject line is missing.",
  "Please attach the document.",
  "The manager replied at 8:30.",
  "This message needs punctuation.",
  "Can you resend the invoice?",
  "I saved the draft already.",
  "The customer asked a question.",
  "Write the full name here.",
  "Email me at work@example.com.",
  "My backup email is user123@test.net.",
  "Please log in with admin_24.",
  "Her username is green.apron7.",
  "The temporary code is A7b9X2.",
  "Use the password: Cat!Tree#9",
  "Reset it before Friday.",
  "The Wi-Fi name is Office_Guest.",
  "Enter code 4829 to continue.",
  "The new login is desk-clerk2.",
  "Check the folder named Reports_2026.",
  "Type this exactly: Qr7!Lm2@.",
  "Use capital letters when needed.",
  "The website ends with .org.",
  "Please update the contact list.",
  "I left a note on your desk.",
  "First, open the program.",
  "Next, type your username.",
  "Then, enter your password.",
  "Last, click the blue button.",
  "Please wash the dishes.",
  "Close the window quietly.",
  "Bring the tray inside.",
  "Take the plates away.",
  "Refill the water pitcher.",
  "Set the table now.",
  "Call the office today.",
  "Answer the phone politely.",
  "Open the cabinet slowly.",
  "Clean the counter well.",
  "I wake up at six.",
  "I eat breakfast at seven.",
  "I go to work early.",
  "My shift starts at nine.",
  "Lunch is at twelve.",
  "Dinner is at six.",
  "I work on Monday.",
  "I work on Tuesday.",
  "I finish work at four.",
  "I take the bus home.",
  "Do you work today?",
  "Do you clean rooms?",
  "Does she answer the phone?",
  "Does he cook dinner?",
  "Yes, I do.",
  "No, I do not.",
  "Yes, she does.",
  "No, he does not.",
  "I do not work today.",
  "She does not cook lunch.",
  "He is making coffee.",
  "They are cleaning the room.",
]

// All keys pt.2
const week_8_curriculum_random = [
  "fr fr ju ju de de ki ki",
  "ws ws ol ol aq aq p; p;",
  "ft ft gh gh yj yj ik ik",
  "rv rv bn bn ce ce m, m,",
  "ty ty ui ui edc edc ik, ik,",
  "qaz wsx edc rfv",
  "pl; okm ijn uhb",
  "rfv tgb yhn ujm",
  "aqz swx dec frv",
  "frt ghy jui kio",
  "1q 2w 3e 4r 5t",
  "6y 7u 8i 9o 0p",
  "a! s@ d# f$ g%",
  "h^ j& k* l( ;)",
  "z1 x2 c3 v4 b5",
  "n6 m7 ,8 .9 /0",
  "q1w2 e3r4 t5y6",
  "a1s2 d3f4 g5h6",
  "z@ x# c$ v% b^",
  "u7i8 o9p0 j-k=",
  "Type this: Hello, world!",
  "Can you type 4/5 correctly?",
  "She said, \"Please sit down.\"",
  "The total is $18.75 today.",
  "Use (parentheses) here.",
  "Add a dash - not a slash /.",
  "The time is 7:45 p.m.",
  "What is your name?",
  "Yes! That is correct.",
  "No, that is not right.",
  "ju ju ju ju",
  "ki ki ki ki",
  "fr fr fr fr",
  "de de de de",
  "ws ws ws ws",
  "ol ol ol ol",
  "aq aq aq aq",
  "p; p; p; p;",
  "rt rt rt rt",
  "yu yu yu yu",
  "gh gh gh gh",
  "vb vb vb vb",
  "nm nm nm nm",
  "edc edc edc edc",
  "rfv rfv rfv rfv",
  "tgb tgb tgb tgb",
  "yhn yhn yhn yhn",
  "ujm ujm ujm ujm",
  "ik, ik, ik, ik,",
  "ol. ol. ol. ol.",
  "p;/ p;/ p;/ p;/",
  "6j 6j 6j 6j",
  "7j 7j 7j 7j",
  "8j 8j 8j 8j",
  "5f 5f 5f 5f",
  "4f 4f 4f 4f",
  "3d 3d 3d 3d",
  "2s 2s 2s 2s",
  "1a 1a 1a 1a",
  "9k 9k 9k 9k",
  "0l 0l 0l 0l",
  "j8 j8 j8 j8",
  "f5 f5 f5 f5",
  "d3 d3 d3 d3",
  "s2 s2 s2 s2",
  "a1 a1 a1 a1",
  "j* j* j* j*",
  "k( k( k( k(",
  "l) l) l) l)",
  "f% f% f% f%",
  "d# d# d# d#",
  "s@ s@ s@ s@",
  "a! a! a! a!",
  "r$ t% y^ u&",
  "e# r$ t% y^",
  "u& i* o( p)",
  "f6 g7 h8 j9",
  "aqz aqz aqz aqz",
  "wsx wsx wsx wsx",
  "cvb cvb cvb cvb",
  "ju7 ju7 uj7y ju7",
  "ki8 ki8 ik8o ki8",
  "fr5 fr5 rf5t fr5",
  "de3 de3 ed3r de3",
  "ws2 ws2 sw2e ws2",
  "ol0 ol0 lo0p ol0",
  "aq1 aq1 qa1w aq1",
  "p;/ p;/ ;p/; p;/",
  "rfv5 rfv5 vr5t frv5",
  "ujm7 ujm7 mu7i jum7",
  "ik,8 ik,8 ki8, ik,8",
  "ol.9 ol.9 lo9. ol.9",
  "edc3 edc3 ce3r dec3",
  "wsx2 wsx2 xs2e swx2",
  "aqz1 aqz1 za1q qaz1",
  "pl/0 pl/0 lp0/ pl/0",
  "frt5 frt5 tr5y ftr5",
  "ghy6 ghy6 yh6u hgy6",
  "bnh7 bnh7 nb7j bhn7",
  "mju8 mju8 um8i jmu8",
  "qw2e qw2e wq2e qe2w",
  "er4t er4t re4t et4r",
  "ty6u ty6u yt6u tu6y",
  "ui8o ui8o iu8o uo8i",
  "as2d as2d sa2d ad2s",
  "df4g df4g fd4g dg4f",
  "gh6j gh6j hg6j gj6h",
  "jk8l jk8l kj8l jl8k",
  "zx2c zx2c xz2c zc2x",
  "cv4b cv4b vc4b cb4v",
  "nm7, nm7, mn7, n,7m",
  "m,8. m,8. ,m8. m.8,",
  "f6j f6j j6f fj6j",
  "d3k d3k k3d dk3d",
  "s2l s2l l2s sl2s",
  "a1; a1; ;1a a;1;",
  "g7h8 g7h8 h7g8 gh78",
  "t5y6 t5y6 y5t6 ty56",
  "r4u7 r4u7 ur47 ru47",
  "e3i8 e3i8 ie38 ei38",
  "w2o9 w2o9 ow29 wo29",
  "q1p0 q1p0 pq10 qp10",
  "f5t6g f5t6g g6t5f ft56g",
  "j7u8h j7u8h h8u7j ju78h",
  "d3r4f d3r4f f4r3d dr34f",
  "k8i9l k8i9l l9i8k ki89l",
  "s2e3d s2e3d d3e2s se23d",
  "l9o0; l9o0; ;0o9l lo90;",
  "a1q2w a1q2w w2q1a aq12w",
  "p0o9i p0o9i i9o0p po09i",
  "z1x2c z1x2c c2x1z zx12c",
  "v4c3x v4c3x x3c4v vc43x",
  "b5v4c b5v4c c4v5b bv54c",
  "n7m8, n7m8, ,8m7n nm78,",
  "m8,9. m8,9. .9,8m m,89.",
  "aq1 ws2 ed3 rf4",
  "pl0 ok9 ij8 uh7",
  "za1 xs2 dc3 fv4",
  "/;0 .l9 ,k8 mj7",
  "fr5 ju7 de3 ki8",
  "gt6 hy7 vb5 nm7",
  "ws2 ol0 aq1 p;/",
  "er4 ui8 df4 jk8",
  "ty6 op0 gh6 l;0",
  "cv4 m,8 zx2 pl0",
  "1qaz 2wsx 3edc 4rfv",
  "7ujm 8ik, 9ol. 0p;/",
  "!a !a a!q !qa",
  "@s @s s@w @ws",
  "#d #d d#e #ed",
  "$f $f f$r $rf",
  "%g %g g%t %tg",
  "^h ^h h^y ^yh",
  "&j &j j&u &uj",
  "*k *k k*i *ik",
  "(l (l l(o (ol",
  ") ; ) ; ;)p )p;",
  "a!q2 a!q2 q!2a aq!2",
  "s@w3 s@w3 w@3s sw@3",
  "d#e4 d#e4 e#4d de#4",
  "f$r5 f$r5 r$5f fr$5",
  "g%t6 g%t6 t%6g gt%6",
  "h^y7 h^y7 y^7h hy^7",
  "j&u8 j&u8 u&8j ju&8",
  "k*i9 k*i9 i*9k ki*9",
  "l(o0 l(o0 o(0l lo(0",
  ";)p- ;)p- p)-; ;p)-",
  "f5t6 y7h6 g6y7 t6h7",
  "d3r4 u8j7 k8i9 e3u8",
  "s2e3 i8k9 l9o0 w2i8",
  "a1q2 p0;-) q1p0 ;0a1",
  "fr5t6g fr5t6g g6t5rf",
  "ju7y8h ju7y8h h8y7uj",
  "de3r4f de3r4f f4r3ed",
  "ki8o9l ki8o9l l9o8ik",
  "ws2e3d ws2e3d d3e2sw",
  "ol9p0; ol9p0; ;0p9lo",
  "aq1w2s aq1w2s s2w1qa",
  "pl0o9k pl0o9k k9o0lp",
  "zx2c3v zx2c3v v3c2xz",
  "m,8.9/ m,8.9/ /9.8,m",
  "q1w2e3 r4t5y6 u7i8o9",
  "a!s@d# f$g%h^ j&k*l(",
  "z1x2c3 v4b5n6 m7,8.9",
  "fr5 ju7 ki8 de3 ws2 ol0",
  "aq1 p;/ zx2 cv4 nm7 m,8",
  "ty6 ui8 op0 gh6 jk8 l;0",
  "q1a! w2s@ e3d# r4f$",
  "t5g% y6h^ u7j& i8k*",
  "o9l( p0;) z1x! c2v@",
  "b5n6 m7,8 .9/0 ;)-=",
  "ws2x ed3c rf4v tg5b",
  "uh7n ij8m ok9, pl0.",
  "aq1z sw2x de3c fr4v",
  "ju7m ki8, lo9. p;0/",
  "f5f j7j d3d k8k",
  "g6g h7h v4v n7n",
  "a1a ;0; s2s l9l",
  "q1q p0p w2w o9o",
  "jsla fdk;",
  "dkas lfj;",
  "flas jkd;",
  "sjdf lak;",
  "asdfg hjkl; gfdsa ;lkjh",
  "aaaa ssss dddd ffff gggg hhhh jjjj kkkk llll ;;;;",
  "aa ss dd ff gg hh jj kk ll ;;",
  "asdfghjkl; asdfghjkl;",
  ";lkjhgfdsa ;lkjhgfdsa",
  "qpwoeiruty tyrueiwoqp",
  "\\ qutew qwwpetuio \\",
  "ruru eiei wowo qpqp",
  "qpqp wowo eiei ruru ttyy",
  "zv xc zv xc zv xc",
  "zxxc cvvz zxxc cvvz",
  "zxc ,./ zxc ,./",
  "v/c. x,z/ v/c. x,z/",
  "zzx ,,x cc/ vv. zzx ,,x cc/ vv.",
  "zxcv zxcv zxcv zxcv",
  "er df cv er df cv",
  "ty gh bn ty gh bn",
  "ui jk nm ui jk nm",
  "op l; ,. op l; ,.",
  "qwer asdf zxcv qwer asdf zxcv",
  "poi ;lkj /.,m poiu ;lkj /.,m",
  "1234567890",
  "!@#$%^&*()",
  "1! 1! 2@ 2@ 3# 3# 4$ 4$",
  "567890 %^&*() 567890",
  "0987612345 )(*&^!@#$",
  "12!@ 34#$ 56%^ 78&* 90()"
]

export { words, phrases, sentences, week_1_curriculum_words, week_1_curriculum_random, week_2_curriculum_words, week_2_curriculum_random, week_3_curriculum_words, week_3_curriculum_random, week_4_curriculum_words, week_4_curriculum_random, week_5_curriculum_words, week_5_curriculum_random, week_6_curriculum_words, week_6_curriculum_random, week_7_curriculum_words, week_7_curriculum_random, week_8_curriculum_words, week_8_curriculum_random };
